export const APP_ROUTE = 'http://localhost:3000'
export const API_ROUTE = 'http://localhost:3005'
export const HOME_ROUTE = '/'
export const CARDS_ROUTE = '/cards'
export const PREVIEW_CARDS_ROUTE = '/previewCards'